name: Deploy to digital ocean

on: push
  # push:
  #   branches: [master]

jobs:
  build_image:
    name: Dockerized app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF//\//-})
      - run: echo ::set-env name=IMAGE_DOCKER_NAME::$(echo ${GITHUB_REPOSITORY})

      - name: Building image and Publish image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: "${{ env.IMAGE_DOCKER_NAME }}/test-github-actions"
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: "latest,${{ env.RELEASE_VERSION }}"

      - name: Deploying to digital ocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: ${{ secrets.SSH_DROPLET_PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker login docker.pkg.github.com -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker pull docker.pkg.github.com/${{ env.IMAGE_DOCKER_NAME }}/test-github-actions:${{ env.RELEASE_VERSION }}
            docker run -dit -p 80:80 docker.pkg.github.com/${{ env.IMAGE_DOCKER_NAME }}/test-github-actions:${{ env.RELEASE_VERSION }}